# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Semantic Pull Request"

on: # yamllint disable-line rule:truthy
    pull_request_target:
        types:
            - "opened"
            - "reopened"
            - "edited"
            - "synchronize"
    merge_group: # yamllint disable-line rule:empty-values

permissions:
    contents: "read"

jobs:
    semantic-pull-request:
        uses: "anolilab/workflows/.github/workflows/semantic-pull-request.yml@main"
        with:
            target-repo: "anolilab/semantic-release"
